name: dev_actions

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: windows-latest
    env:
      Source: ${{secrets.PUBLISH_SOURCE}}
      Dest: ${{secrets.PUBLISH_DEST}}
      Username: ${{secrets.USERNAME}}
      ComputerName: ${{secrets.COMPUTER_NAME}}
      Password: ${{secrets.PASSWORD}} 
      

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Caching
      id: cache
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: ${{ runner.os }}-nuget-   
    - name: Restore dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: publish
      run: dotnet publish --no-build 
    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'
    #- name: artifact_upload
     # uses: actions/upload-artifact@v2
     # with:
     #   name: generate_build_artifact
     #   path: D:\a\CI_CD_training\CI_CD_training\Ci_Cd_DemoApp\bin\Debug\netcoreapp3.1\publish\
   # - name: Stop Application Pool
    #  shell: cmd
     # run: '"C:/Program Files (x86)/IIS/Microsoft Web Deploy V3/msdeploy.exe" -verb:sync -allowUntrusted -source:recycleApp -dest:recycleApp="MySite",recycleMode="StopAppPool",computerName="${{ env.ComputerName }}",username="${{ env.Username }}",password="${{ env.Password }}",authtype="Basic"'
    #- name: Deploy Application to Livee  
     # shell: cmd  
     # run: '"C:/Program Files (x86)/IIS/Microsoft Web Deploy V3/msdeploy.exe" -source:contentPath="${{ env.Source }}" -dest:contentPath="${{ env.Dest}}",computerName="${{ env.ComputerName }}",username="${{ env.Username }}",password="${{ env.Password }}",authtype="Basic",includeAcls="False" -verb:sync -useCheckSum -disableLink:AppPoolExtension -disableLink:ContentExtension -disableLink:CertificateExtension -allowUntrusted'
    #- name: Start Application Pool
    #  shell: cmd
    #  run: '"C:/Program Files (x86)/IIS/Microsoft Web Deploy V3/msdeploy.exe" -verb:sync -allowUntrusted -source:recycleApp -dest:recycleApp="MySite",recycleMode="StartAppPool",computerName="${{ env.ComputerName }}",username="${{ env.Username }}",password="${{ env.Password }}",authtype="Basic"'
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: Cicddemo
        environment_name: Cicddemo-env
        version_label: 12345
        region: ap-south-1
        deployment_package: deploy.zip
